version: '3.8'

services:
  beauty-store:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beauty-store-app
    restart: unless-stopped
    expose:
      - "3000" # Exponer el puerto 3000 sin mapearlo a un puerto específico del host
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    networks:
      - beauty-store-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  beauty-store-network:
    driver: bridge
